# Generated by Django 5.1.5 on 2025-02-14 02:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('patronymic', models.CharField(blank=True, max_length=128)),
                ('school', models.CharField(default='Школа, номер. Образец [ГБОУ Школа № 853] ', max_length=100)),
                ('class_number', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(11)])),
                ('class_litera', models.CharField(blank=True, max_length=1)),
                ('birth_year', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(3000)])),
                ('student_status', models.CharField(default='Информация отсутствует.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('date', models.DateField(verbose_name='2025 02 14')),
                ('school', models.CharField(default='', max_length=100)),
                ('answer_1A', models.CharField(blank=True, max_length=512)),
                ('answer_1B', models.CharField(blank=True, max_length=512)),
                ('answer_2A', models.CharField(blank=True, max_length=512)),
                ('answer_2B', models.CharField(blank=True, max_length=512)),
                ('answer_3A', models.CharField(blank=True, max_length=512)),
                ('answer_3B', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='test_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_answer_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('date', models.DateField(verbose_name='2025 02 14')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('answer_1A', models.CharField(blank=True, max_length=512)),
                ('answer_1B', models.CharField(blank=True, max_length=512)),
                ('answer_2A', models.CharField(blank=True, max_length=512)),
                ('answer_2B', models.CharField(blank=True, max_length=512)),
                ('answer_3A', models.CharField(blank=True, max_length=512)),
                ('answer_3B', models.CharField(blank=True, max_length=512)),
                ('student_status', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='Школа, номер. Образец [ГБОУ Школа № 853] ', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
