# Generated by Django 5.1.5 on 2025-02-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='answer_1A',
            new_name='question_1A',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='answer_1B',
            new_name='question_1B',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='answer_2A',
            new_name='question_2A',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='answer_2B',
            new_name='question_2B',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='answer_3A',
            new_name='question_3A',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='answer_3B',
            new_name='question_3B',
        ),
    ]
