# Generated by Django 5.1.5 on 2025-02-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0003_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(default='Школа, номер. Образец: ГБОУ Школа № 853', max_length=100),
        ),
    ]
