# Generated by Django 5.1.5 on 2025-02-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0004_alter_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_answer',
            name='test_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
