# Generated by Django 5.1.5 on 2025-02-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0005_test_answer_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_answer',
            name='answer_1A',
        ),
        migrations.RemoveField(
            model_name='test_answer',
            name='answer_1B',
        ),
        migrations.RemoveField(
            model_name='test_answer',
            name='answer_2A',
        ),
        migrations.RemoveField(
            model_name='test_answer',
            name='answer_2B',
        ),
        migrations.RemoveField(
            model_name='test_answer',
            name='answer_3A',
        ),
        migrations.RemoveField(
            model_name='test_answer',
            name='answer_3B',
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_1A1',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_1A2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_1A3',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_1B1',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_1B2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_1B3',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_2A1',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_2A2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_2A3',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_2B1',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_2B2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_2B3',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_3A1',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_3A2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_3A3',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_3B1',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_3B2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='answer_3B3',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
