# Generated by Django 5.1.5 on 2025-02-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0006_remove_test_answer_answer_1a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='students_class',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test_answer',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='test_answer',
            name='student_status',
            field=models.CharField(max_length=100),
        ),
    ]
