# Generated by Django 5.1.5 on 2025-02-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0007_test_students_class_alter_test_answer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='students_litera',
            field=models.CharField(default='', max_length=100),
        ),
    ]
