# Generated by Django 5.1.5 on 2025-02-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0009_test_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='test',
            name='students_class',
        ),
        migrations.RemoveField(
            model_name='test',
            name='students_litera',
        ),
        migrations.AddField(
            model_name='test_answer',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='students_class',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='students_litera',
            field=models.CharField(default='', max_length=100),
        ),
    ]
