# Generated by Django 5.1.5 on 2025-02-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0010_remove_test_checked_remove_test_students_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='students_class',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='students_litera',
            field=models.CharField(default='', max_length=100),
        ),
    ]
