# Generated by Django 5.1.5 on 2025-02-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0011_test_checked_test_students_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, default='М/Ж', max_length=3),
        ),
    ]
