# Generated by Django 5.1.5 on 2025-02-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0013_remove_student_patronymic_test_answer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
