# Generated by Django 5.1.5 on 2025-02-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_complex', '0014_student_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_answer',
            name='gender',
            field=models.CharField(blank=True, default='М/Ж', max_length=3),
        ),
    ]
